### ISSUE TITLE
Disable Activity Logging or anonymize IPs

### ISSUE THREAD

**Issue by TobiasMende** [webgrafia/ginger#14]
Is there any possibility to disable the Activity Logger or at least anonymize the IPs? 

As far as I understand, storing the full IPs of every user that accepts or declines cookies may not comply to the new EU data protection laws.

What do you think?

**Comment by webgrafia** [comment]
You're right, I will add a flag to explicitally enable logger.
But is a mess of time, if you or someone else want make a pull request I will accept it quickly!

**Comment by TobiasMende** [comment]
Thanks for your response!
I will have a look how this can be accomplished. But I cannot promise that I am able to find a good solution since my PHP knowledge is a bit outdated.
