### ISSUE TITLE
Google Analytics opt in

### ISSUE THREAD

**Issue by PixelhafenDesign** [webgrafia/ginger#17]
Whats about a google analytics opt in option. I'am from germany and must give my visitors a possibilty to opt in or opt out of google analytics, so no cookies can be set without an agreement of them.

**Comment by webgrafia** [comment]
As I know is not necessary an agreement if ip is anonymized.
Ginger actually make google analytics anonimyzed (with last numbers of IP hidden) until user don't accept cookie.

**Comment by HartLarsson** [comment]
Before consent every analytics cookies must be disabled. This is because there is the possibility that on the tracker there is enabled the remarketing features.

**Comment by PixelhafenDesign** [comment]
That's why I asked about the Opt in function. So that Google Analytics is already deactivated when visiting pages and only becomes active if you have agreed.
